# Generated by Django 3.1.3 on 2020-11-21 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gameboard', '0004_gamepiece'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='img/profile/')),
                ('profile_game_piece', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gameboard.gamepiece')),
            ],
        ),
    ]
