# Generated by Django 3.1.3 on 2020-11-24 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameboard', '0004_gamepiece'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_game_piece',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piece', to='gameboard.gamepiece'),
        ),
    ]
