# Generated by Django 3.1.3 on 2020-11-16 20:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gameboard', '0002_playergameboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameboard',
            name='gameboard_players',
            field=models.ManyToManyField(through='gameboard.PlayerGameboard', to=settings.AUTH_USER_MODEL),
        ),
    ]
