# Generated by Django 3.1.3 on 2020-11-21 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameboard', '0003_gameboard_gameboard_players'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece_name', models.CharField(max_length=200)),
                ('piece_pic', models.ImageField(upload_to='image/pieces/')),
            ],
        ),
    ]
