# Generated by Django 3.1.3 on 2020-11-21 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='award_created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
