# Generated by Django 3.1.3 on 2020-11-24 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameboard', '0004_gamepiece'),
        ('awards', '0002_auto_20201121_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='player_gameboard_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_gameboard', to='gameboard.playergameboard'),
        ),
    ]
